### ISSUE TITLE
Sapper still works in friendly

### ISSUE THREAD

**Issue by Darkita162** [DFS-Servers/BugReportsAndSuggestions#299] opened 2021-02-21 18:22 UTC
**Describe the bug**
When a spy is in friendly, the sapper, doesn't matter which one, still works as normal.
**Expected behavior**
What you expected to happen instead of the bug.
Sapper not be able to attach itself to buildings
**To Reproduce**
Describe the steps to take to reproduce the bug.

Go into friendly
go spy
aim sapper and place on enemy building
still works as if you're not in friendly

**Server Info (please complete the following information):**
 - Region & IP:  EU, 89.35.29.11:27145

**Comment by Mikusch** [comment] 2021-02-21 18:30
Duplicate of #293

**Closed** 2021-02-21 18:44 UTC
