### ISSUE TITLE
Bugged map: ctf_steamroll Caps not counting, traps players in traintrack spawn once they die.

### ISSUE THREAD

**Issue by miniz1994** [DFS-Servers/BugReportsAndSuggestions#164] opened 2019-07-29 11:41 UTC
**Steam Profile**
https://steamcommunity.com/id/miniz1994/

**Describe the bug**
Map doesnt seem too count the caps done & also seems a bit odd that on death it just permanently puts you on the train track spawn until the round is over.

**To Reproduce**
Play the map & decide what too do with it.

**Expected behavior**
Caps should ofc count & im not sure if its supposed too just leave people spawning on the traintracks until the round is over.

**Server Info (please complete the following information):**
EU, but im certain it does this on USA as well.

**Comment by GreenSwede** [comment] 2019-08-03 16:25
Caps do count, however we have no flag capture limit on the map (tf_flag_caps_per_round is set to 0 on all CTF maps) which automatically causes a stalemate after the round limit. Spawning on the track when you get killed appears to be intended, so it's not a bug.

It feels like it's a mix of CTF and Arena on this map. To play it the intended way we need a capture limit (maybe 3? I don't know what the cap is intended to be by the map's creator). The timelimit after 1 cap is done is 60 seconds, and the team with the most caps win.

@Dispenz0r Would it be possible to set a flag capture limit on this map?

**Comment by Light08** [comment] 2019-08-04 14:40
Set flag capture limit to 1. It is indeed intended to be a small, arena-like gamemode. The point is to either 
A. Kill every enemy
B. Capture the intel, alive.

**Comment by Dispenz0r** [comment] 2019-08-05 22:18
Should be fixed now, thanks for reporting.

**Closed by Dispenz0r** 2019-08-05 22:18 UTC
Labels: :open_file_folder: Specific Map
