### ISSUE TITLE
Escape Not Working in Slender

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#209] opened 2019-11-24 16:04 UTC
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/

**Describe the bug**
In Slender Fortress, specifically on the map slender_manor_final1, occasionally the escape trigger will not work, resulting in running into the space at the back of the spawn room not teleporting you out of the play space, displaying the relevant chat message, etc.

I, personally, have only encountered this bug once, while Dark Isabelle was the active boss. Others have reported encountering the same problem, but I am not aware of what the active boss was in these cases.

**To Reproduce**
1. Load slender_manor_final1
2. Collect all flasks
3. Attempt to escape

**Expected behavior**
You should be able to escape as normal.

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/42521633/69497362-efa9ea80-0ed3-11ea-80b4-beb982f4c1ad.png)

**Server Info**
EU 89.35.29.11:27145

**Comment by Dispenz0r** [comment] 2019-11-25 15:27
We tried reproducing this issue multiple times on multiple slender maps including slender_manor but haven't been able to get it once ever, there are also no error logs and the author(s) of the plugins have no idea what this could be caused by.

Closing

**Comment by Dispenz0r** [comment] 2019-11-29 12:43
Reopening, might have a fix for this sooner or later

**Comment by Dispenz0r** [comment] 2020-01-01 13:29
This should hopefully be fixed now

**Closed by Dispenz0r** 2020-01-01 13:29 UTC
Labels: :bug: Bug, :flags:Specific Gamemode
