### ISSUE TITLE
[SZF] Spy Left Cloaking Arm Bug

### ISSUE THREAD

**Issue by MrAori** [DFS-Servers/BugReportsAndSuggestions#132] opened 2019-05-16 18:40 UTC
**Steam Profile**
https://steamcommunity.com/id/mrcallie/

**Describe the bug**
Basically, spy's left cloaking arm shows up on all of the classes viewmodels when I get changed to a different special infected, happened to be tank when I first got the bug, when I'm either a stalker that is still cloaked or sometimes when you are cloaked as a regular spy zombie.

**To Reproduce**
Describe the steps to reproduce the bug.
1. Be a Spy or stalker and make sure you are cloaked.
2. Wait till you get spawned as a different special infected (e.g. Boomer)
3. Once you are spawned as that special unit, the arm bug appears, even at the next round.

**Expected behavior**
The arm should not be there when you changed into a different special infected and cloaked at the same time.

**Screenshots or error logs**
![Image of the Bug](https://user-images.githubusercontent.com/42550826/57878589-43939280-7812-11e9-9e4e-fa1e6b20094e.png)

**Server Info (please complete the following information):**
Dispenz0r's Fun Server [EU]
IP: 89.35.29.11:27145

**Additional context**
A temporary fix of this you cloak and de-cloak as a spy again and it should remove it.

**Comment by shinsasch** [comment] 2019-05-16 18:45
So the previous report of this said how it is reproduced, the problem is, I literally cannot reproduce this. So I am not sure what exactly is to be fixed or what steps to take to fix this. So this won't be fixed anytime soon, unfortunately.

**Comment by shinsasch** [comment] 2019-05-20 14:57
i forgot that i have autoexecs on the spy (and some other classes) that disable the viewmodel, so i was never able to see the bug in action :sweat: bruh moment

**Comment by shinsasch** [comment] 2019-05-20 14:57
should be fixed after this maintenance though.

**Comment by Dispenz0r** [comment] 2019-05-20 15:58
Thanks for the bug report and bug fix, the patch should be applied in an upcoming small hotfix patch really soon.

**Comment by Dispenz0r** [comment] 2019-05-27 12:04
Patch should be applied now

**Closed by Dispenz0r** 2019-05-27 12:04 UTC
Labels: :bug: Bug, :flags:Specific Gamemode
