### ISSUE TITLE
"Toxic" roll the dice effect doesn't work.

### ISSUE THREAD

**Issue by qli-p** [DFS-Servers/BugReportsAndSuggestions#252] opened 2020-05-08 20:03 UTC
Steam Profile

https://steamcommunity.com/id/supermareoinrealloife/

Describe the bug:

Upon rolling toxic, the player will only recieve the red particle effect, but will do no damage to surrounding players, not even after a kill (even though I'm pretty sure its supposed to work without getting any prior kills; I'm just mentioning this incase a kill requisite was implemented, or something)

Expected behavior: 

The player will slowly deal damage to those surrounding if under the effect of toxic.

**Comment by Dispenz0r** [comment] 2020-05-11 20:53
Seems to work perfectly fine after doing some testing, the aura of this effect should be lower than usual but works as intended. 

Maybe you were on a friendly map while using it without realizing it? Either way I'll be closing this for now.

**Closed by Dispenz0r** 2020-05-11 20:53 UTC
