### ISSUE TITLE
Daily did not reset

### ISSUE THREAD

**Issue by Kray0la** [DFS-Servers/BugReportsAndSuggestions#36] opened 2018-08-29 15:36 UTC
**Describe the bug**
See title. The daily has not been reset from yesterday even though it was supposed to be this midnight.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots or error logs**
https://i.imgur.com/9nbpWCt.png
https://i.imgur.com/la16pfd.png

**Server Info (please complete the following information):**
 - Region: EU / UK
 - IP 89.35.29.11:27145

**Additional context**
The quest that I got was a Medic Kill/Assist Quest.

**Comment by ramunecarbonated** [comment] 2018-08-29 16:01
will see if i can reproduce the intended process of quest resets on my localhost

**Comment by Dispenz0r** [comment] 2018-08-29 16:02
I just refreshed the daily quests manually for now, until we can fix it to be automatic.

Let us know if it persists tomorrow or so.

**Comment by ramunecarbonated** [comment] 2018-08-29 17:16
Procedure succesfully executed locally. Involving @GreenSwede as there a probably a mistake in installation / setting up the cronjob.

**Comment by ramunecarbonated** [comment] 2018-08-30 13:52
@GreenSwede adjusted the cronjobs and according to @Dispenz0r and Limey it is now working as intended, so closing. :confetti_ball:

**Comment by Kray0la** [comment] 2018-08-30 18:53
I sadly have to de-confirm that the issue still persists on my end. The quest you see here was, again, from yesterday, and it was not reset for unknown reasons. https://i.imgur.com/1N19ZkX.png

**Comment by ramunecarbonated** [comment] 2018-08-31 11:56
Since the issue is outside of my scope now I will be unassigning myself, the others are hard at work however to diagnose the exact issue. Seems for some their quest cooldowns do get reset and for most they don't.

**Comment by Dispenz0r** [comment] 2018-09-01 14:01
This problem should now be solved big thanks to @GreenSwede 

Closing.

**Closed by Dispenz0r** 2018-09-01 14:01 UTC
Labels: :bug: Bug, :cold_sweat: Help wanted
