### ISSUE TITLE
Round End Bug in VSH

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#95] opened 2019-01-26 00:03 UTC
**Steam Profile**
https://steamcommunity.com/id/thatlimeball/, submitting this bug on behalf of https://steamcommunity.com/id/domegastar/

**Describe the bug**
If the Administrator uses her Resurrect ability when the round ends, the RED players who were switched to BLU Team will not be switched back and the round will be stuck waiting as if there are not enough players to continue.

**To Reproduce**
1. Use the Administrator's Resurrect ability as a round ends

**Expected behavior**
The round should end without any problems, switching all resurrected players  and the boss back to RED and switching the next boss player to BLU.

**Server Info (please complete the following information):**
US | VA

**Comment by Benoist3012** [comment] 2019-01-26 12:52
While not being an actual bug from the mod but rather an issue with Arena itself (by Valve in fact), I'll "fix" it anyway. This isn't because of vsh in any way, try any arena based gamemode and have everyone in the same team, the round will not restart.

**Comment by Benoist3012** [comment] 2019-01-26 13:02
Alright I dispatched a fix, I'll now monitor the effects and leave this issue open.
@Dispenz0r close this issue when the valve bug is confirmed as resolved.

**Comment by Benoist3012** [comment] 2019-01-28 12:42
I'm gonna ahead and consider this working. Please open it again if issue still occurs.

**Closed by Benoist3012** 2019-01-28 12:42 UTC
Labels: :flags:Specific Gamemode, :video_game::bug: Server Bug Report

**Comment by Dispenz0r** [comment] 2019-01-28 13:08
Community Box given now, thanks for reporting!
