### ISSUE TITLE
dr_firetemple_b4a progression stopper

### ISSUE THREAD

**Issue by Limeball** [DFS-Servers/BugReportsAndSuggestions#40] opened 2018-08-31 15:28 UTC
**Steam Profile**
https://steamcommunity.com/id/thatlimey/

**Describe the bug**
The hammer on dr_firetemple_b4a cannot be picked up, blocking player progression through the map as the hammer is needed to break certain blocks to continue.

**To Reproduce**
1. Reach the hammer on dr_firetemple_b4a
2. Stand on the hammer

**Expected behavior**
The hammer will not be picked up, and players cannot progress through the map.

**Screenshots or error logs**
![image](https://user-images.githubusercontent.com/42521633/44921464-8a039880-ad3a-11e8-9b4d-340e569efc3c.png)

**Server Info (please complete the following information):**
EU | UK - 89.35.29.11:27145 

**Additional context**
Interestingly, picking up Small Keys still works. These work in the same way, activating some kind of map trigger when a player touches it.

**Comment by Dispenz0r** [comment] 2018-08-31 22:25
Oof, how troublematic.

Nothing we can do about this until the map author somehow sees this issue and decides to fix it, otherwise I'll be forced to remove and replace the map with another seeing how major the problem is.

**Comment by Dispenz0r** [comment] 2018-09-03 01:11
Just to confirm, is this still happening?

Try to reproduce it one more time if you can

**Comment by Dispenz0r** [comment] 2018-09-04 15:55
I assume this was a rare one time thing and will be closing it, if you see it happening again feel free to open another issue about it.

**Closed by Dispenz0r** 2018-09-04 15:55 UTC
Labels: :bug: Bug, :file_folder: Specific Server/Map
